import {
  CheckCircleIcon,
  WarningIcon,
  StarIcon,
  CheckIcon,
  ChatIcon,
} from "@chakra-ui/icons";

// Adoption action configurations
export const ADOPTION_ACTION_CONFIGS = {
  withdraw: {
    label: "Withdraw Application",
    buttonLabel: "Withdraw Application",
    variant: "solid" as const,
    colorScheme: "red" as const,
    icon: WarningIcon,
    requiresPayment: false,
    disabled: false,
  },
  message: {
    label: "Send Message",
    buttonLabel: "Send Message",
    variant: "outline" as const,
    colorScheme: "blue" as const,
    icon: ChatIcon,
    requiresPayment: false,
    disabled: false,
  },
  reserve: {
    label: "Reserve Pet",
    buttonLabel: "Pay Reservation Fee",
    variant: "solid" as const,
    colorScheme: "green" as const,
    icon: CheckIcon,
    requiresPayment: true,
    disabled: false,
  },
  approve: {
    label: "Approve Application",
    buttonLabel: "Approve Application",
    variant: "solid" as const,
    colorScheme: "green" as const,
    icon: CheckCircleIcon,
    requiresPayment: false,
    disabled: false,
  },
  reject: {
    label: "Reject Application",
    buttonLabel: "Reject Application",
    variant: "solid" as const,
    colorScheme: "red" as const,
    icon: WarningIcon,
    requiresPayment: false,
    disabled: false,
  },
  complete: {
    label: "Complete Adoption",
    buttonLabel: "Complete Adoption",
    variant: "solid" as const,
    colorScheme: "blue" as const,
    icon: CheckIcon,
    requiresPayment: false,
    disabled: false,
  },
  leave_review: {
    label: "Leave Review",
    buttonLabel: "Leave Review",
    variant: "solid" as const,
    colorScheme: "purple" as const,
    icon: StarIcon,
    requiresPayment: false,
    disabled: false,
  },
};
